name: Gerar Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar sitemap.xml manualmente
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          find . -name '*.html' | while read html_file; do
            url_path=$(echo $html_file | sed 's|^\./||')
            echo "  <url>" >> sitemap.xml
            echo "    <loc>https://www.odespertardosreinos.com.br/$url_path</loc>" >> sitemap.xml
            echo "    <changefreq>monthly</changefreq>" >> sitemap.xml
            echo "    <priority>0.5</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit e Push do sitemap.xml
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sitemap.xml
          git commit -m "Atualiza sitemap.xml" || echo "Nada novo para commitar"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
