name: Gerar Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          sitemap_format: xml
          base_url: https://www.odespertardosreinos.com.br

      - name: Commit sitemap.xml
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sitemap.xml
          git commit -m "Adiciona sitemap.xml" || echo "Nada para commitar"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
